// <auto-generated />
namespace Ufostranky.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class whoops : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(whoops));
        
        string IMigrationMetadata.Id
        {
            get { return "201409260905445_whoops"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
